import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer"; 
import DarkModeToggle from "@/components/DarkModeToggle";


const outfit = Outfit({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "DETRONE",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", 
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <ClerkProvider afterSignOutUrl="/sign-up">
      <html lang="en">
        <body className={outfit.className}>
          <NavBar />
          <div className="flex justify-end p-4">
            <DarkModeToggle /> 
          </div>
          <main className="flex-grow pb-32">{children}</main>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
    
  );
}
